spring:
  flyway:
    locations: classpath:db/migration/common
  datasource:
    username: postgres
    password: P@ssw0rd
    url: jdbc:postgresql://localhost:5432/qyoga
  servlet:
    multipart:
      max-file-size: 1MB
qyoga:
  hash:
    secret-key: secret-key
#54501