spring:
  flyway:
    locations: classpath:db/migration/common
  datasource:
    username: postgres
    password: password
    url: jdbc:postgresql://localhost:54501/qyoga
  servlet:
    multipart:
      max-file-size: 1MB

debug: false