version: '3'

name: elta-infra

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: P@ssw0rd
      POSTGRES_DB: qyoga
      PGDATA: var/lib/postgresql/data/pgdata
    volumes:
      - /var/pgdata/qyoga:/var/lib/postgresql/data/pgdata

    ports:
      - "54501:5432"