# Проект test-инфраструктуры
# test-инфраструктура хранит данные на docker tmpfs volume (данные не переживают перезапуск контейнера)
# Тесты настроенны таким образом, что на старте пытаются подключиться к тестовой инфраструктуре и
# запускают контейнеры через testcontainers только если не получается

version: '3'

name: qyoga-tests-infra

services:

  postgres:
    extends:
      file: docker-compose-infra-base.yml
      service: postgres

    container_name: qg-pg-tests

    environment:
      PGDATA: /tmp/pgdata

    tmpfs:
      - /tmp

    ports:
      - "54502:5432"