# Базовый проект для инфраструктуры

version: '3.8'

name: qyoga-infra

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qyoga
      PGDATA: /var/lib/postgresql/data/pgdata