# Базовый проект для инфраструктуры

version: '3.8'

name: qyoga-infra

services:

  postgres:
    image: postgres:15.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: qyoga
      PGDATA: /var/lib/postgresql/data/pgdata


  minio:
    image: minio/minio:RELEASE.2024-01-16T16-07-38Z
    container_name: minio
    environment:
      MINIO_ROOT_USER: user
      MINIO_ROOT_PASSWORD: password
      MINIO_VOLUMES: /var/data/qyoga/minio

    command: server
