# Проект для локальной отладки в контейнере
# Собирает образ приложения на базе текущего состояния рабочей директории и запускает систему целиком

name: qyoga-system-dev

services:

  app:
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qyoga
      - SPRING_PROFILES_ACTIVE=prod,demo
      - MINIO_ENDPOINT=http://minio:9000

    build:
      context: ../../
      dockerfile: deploy/qyoga/Dockerfile

    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    links:
      - "postgres:database"
      - "minio:minio"
