# Проект dev-инфраструктуры
# dev-инфраструктура хранит данные на docker volume (данные переживают перезапуск контейнера, но не его удаление)
# На этот проект настроена интеграция Spring Boot с Docker Compose (при необходимости, Спринг автоматически запускает проект на старте)

version: '3'

name: qyoga-infra-dev

services:

  postgres:
    extends:
      file: docker-compose-infra-base.yml
      service: postgres

    container_name: qg-pg-dev

    ports:
      - "54501:5432"


  minio:
    extends:
      file: docker-compose-infra-base.yml
      service: minio

    container_name: qg-minio-dev

    ports:
      - "50000:9000"
