# Проект для прода

version: '3'

services:

  postgres:
    extends:
      file: docker-compose-infra-base.yml
      service: postgres
    logging:
      driver: journald
    restart: always
    volumes:
      - /var/pgdata/qyoga:/var/lib/postgresql/data/pgdata

  minio:
    extends:
      file: docker-compose-infra-base.yml
      service: minio
    logging:
      driver: journald
    restart: always

  app:
    logging:
      driver: journald
    image: ghcr.io/d-r-q/qyoga:latest
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/qyoga
      - SPRING_PROFILES_ACTIVE=prod,prod-secrets

    restart: always

    depends_on:
      - postgres
      - minio
    ports:
      - "8080:8080"
    links:
      - "postgres:database"